version: '3'
services:
  mongodb:
    image: mongo:latest
  
  web:
    image: demo:latest
    ports:
      - 80:80
  
  api:
    image: demo-api:latest
    ports:
      - 3000:3000
    links:
      - mongodb:mongodb
  
  jenkins:
    image: jenkinsci/blueocean:1.3.3
    ports:
      - 8080:8080
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
    
  